# Generated by Django 4.0.5 on 2022-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0002_alter_record_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category_display',
            field=models.CharField(default='cash', max_length=200),
            preserve_default=False,
        ),
    ]
