# Generated by Django 4.0.5 on 2022-06-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0003_record_category_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='repository',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE,
                                    to='repository.repository'),
            preserve_default=False,
        ),
    ]
