# Generated by Django 4.0.5 on 2022-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0006_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
