# Generated by Django 4.0.5 on 2022-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('repository', '0008_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
