# Generated by Django 4.0.5 on 2022-06-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_remove_record_category_remove_record_repository_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='cart',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='cash',
        ),
    ]
