# Generated by Django 4.0.5 on 2022-06-13 13:32

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_record_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
