# Generated by Django 4.0.5 on 2022-06-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('repository', '0011_remove_record_category_remove_record_repository_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('cart', 'کارت')], max_length=30)),
                ('record_type', models.CharField(choices=[('input', 'دریافتی'), ('output', 'مخارج')], max_length=30)),
                ('price', models.IntegerField()),
                ('date', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='category.category')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='repository.repository')),
            ],
        ),
    ]
